spring.application.name=ParkPoint

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog-master.xml

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/parkPoint
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate

logging.level.root=INFO
logging.level.ru.vaschenko.ParkPoint=DEBUG
logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=5

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html